# Generated by Django 6.0.2 on 2026-05-03 14:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('language', models.CharField(default='en', max_length=5)),
                ('district', models.CharField(blank=True, default='', max_length=50)),
                ('trade', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('language', models.CharField(db_index=True, max_length=5)),
            ],
            options={
                'ordering': ['language', 'question_id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(default='en', max_length=5)),
                ('audio_base64', models.TextField(blank=True, default='')),
                ('keyframes', models.JSONField(blank=True, default=list)),
                ('transcript', models.TextField(blank=True, default='')),
                ('relevance_score', models.FloatField(default=0.0)),
                ('completeness_score', models.FloatField(default=0.0)),
                ('clarity_score', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('category', models.CharField(blank=True, default='', max_length=30)),
                ('integrity_flag', models.BooleanField(default=False)),
                ('integrity_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='interview.candidate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='interview.question')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'question'), name='unique_candidate_question')],
            },
        ),
    ]
